name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  publish-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install hatch

      - name: Build Wheel
        run: cd python && hatch build

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: python/dist/*

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
